const config = {
    EXPO_PUBLIC_FIREBASE_KEY: process.env.EXPO_PUBLIC_FIREBASE_KEY ?? "",
    EXPO_PUBLIC_FIREBASE_AUTHDOMAIN: process.env.EXPO_PUBLIC_FIREBASE_AUTHDOMAIN ?? "",
    EXPO_PUBLIC_FIREBASE_PROJECTID: process.env.EXPO_PUBLIC_FIREBASE_PROJECTID ?? "",
    EXPO_PUBLIC_FIREBASE_STORAGEBUCKET: process.env.EXPO_PUBLIC_FIREBASE_STORAGEBUCKET ?? "",
    EXPO_PUBLIC_FIREBASE_SENDERID: process.env.EXPO_PUBLIC_FIREBASE_SENDERID ?? "",
    EXPO_PUBLIC_FIREBASE_APPID: process.env.EXPO_PUBLIC_FIREBASE_APPID ?? "",
  
};
export default config;